import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marketing Group",
  description: "Generated by create next app",
};

export default function MarketingLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="w-full h-[80px] bg-black/80 justify-center items-center flex"><p className="text-white font-extrabold">Header</p></header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1>Mi titulo</h1>
        {children}
      </body>
      <footer>
        <div className="flex">
          <p>footer</p>
          <p>footer</p>
        </div>
      </footer>
    </html>
  );
}
